- name: install vital packages
  apt:
    name: 
      - software-properties-common
      - ecryptfs-utils
      - cryptsetup
      - vim
      - tmux
      - curl
      - cifs-utils      # mount.cifs (NFS)
      - net-tools       # netstat
      - nmap
  become: yes
