- name: install thunderbird
  block:
    - name: add thunderbird repository
      apt_repository:
        repo: ppa:ubuntu-mozilla-daily/ppa

    - name: install thunderbird
      apt:
        name: thunderbird
  become: yes

